version: '3.8'

services:

  java:
    image: teja123456789/java
    ports:
      - "80:80"
    deploy:
      replicas: 3

  python:
    image: teja123456789/python
    ports:
      - "81:80"
    deploy:
      replicas: 3

  acos:
    image: teja123456789/aws
    ports:
      - "82:80"
    deploy:
      replicas: 3
